### ISSUE TITLE
NBT标签中引号的转义识别问题

### ISSUE THREAD

**Issue by NearlyHeadlessJack** [CPJiNan/AkariCDK#1]
```
    - command inline "give @p minecraft:diamond_sword{display:{Name:\'[\"干将莫邪\"]\'},Enchantments:[{id:\"minecraft:sharpness\",lvl:5s},{id:\"minecraft:vanishing_curse\",lvl:1s},{id:\"minecraft:fire_aspect\",lvl:2s},{id:\"minecraft:knockback\",lvl:2s},{id:\"minecraft:looting\",lvl:3s}]}"
```
会报错
<img width="270" alt="image" src="https://user-images.githubusercontent.com/56494680/215221206-c035782d-4408-4c95-af5f-70a95ed8386c.png">
不打`\`则会报错
<img width="287" alt="image" src="https://user-images.githubusercontent.com/56494680/215221258-dcf28fe0-7c14-4549-8266-7d90f9299434.png">

**Comment by CPJiNan** [comment]
建议使用物品库类型的插件替代原版指令。

[RPG|管理] NeigeItems —— 万能随机物品库 [1.12.2-1.19.3]
https://www.mcbbs.net/thread-1364195-1-1.html
(出处: Minecraft(我的世界)中文论坛)

**Comment by NearlyHeadlessJack** [comment]
这是来自QQ邮箱的自动回复邮件。你好，已收悉，感谢您的支持。

**Comment by NearlyHeadlessJack** [comment]
现在又有个这个问题，普通玩家兑换物品（give指令）会这样我用的lp管理权限是哪里的权限节点不合适吗？发自我的 iPhone在 2023年1月28日，10:07，季楠 ***@***.***> 写道：﻿
建议使用物品库类型的插件替代原版指令。
[RPG|管理] NeigeItems —— 万能随机物品库 [1.12.2-1.19.3]
https://www.mcbbs.net/thread-1364195-1-1.html
(出处: Minecraft(我的世界)中文论坛)

**Comment by NearlyHeadlessJack** [comment]
I’m sorry but you do not have permission to perform this command发自我的 iPhone在 2023年1月28日，23:01，1217423985 ***@***.***> 写道：﻿现在又有个这个问题，普通玩家兑换物品（give指令）会这样我用的lp管理权限是哪里的权限节点不合适吗？发自我的 iPhone在 2023年1月28日，10:07，季楠 ***@***.***> 写道：﻿
建议使用物品库类型的插件替代原版指令。
[RPG|管理] NeigeItems —— 万能随机物品库 [1.12.2-1.19.3]
https://www.mcbbs.net/thread-1364195-1-1.html
(出处: Minecraft(我的世界)中文论坛)

**Comment by NearlyHeadlessJack** [comment]
我知道问题所在了，没写as op发自我的 iPhone在 2023年1月28日，23:02，1217423985 ***@***.***> 写道：﻿I’m sorry but you do not have permission to perform this command发自我的 iPhone在 2023年1月28日，23:01，1217423985 ***@***.***> 写道：﻿现在又有个这个问题，普通玩家兑换物品（give指令）会这样我用的lp管理权限是哪里的权限节点不合适吗？发自我的 iPhone在 2023年1月28日，10:07，季楠 ***@***.***> 写道：﻿
建议使用物品库类型的插件替代原版指令。
[RPG|管理] NeigeItems —— 万能随机物品库 [1.12.2-1.19.3]
https://www.mcbbs.net/thread-1364195-1-1.html
(出处: Minecraft(我的世界)中文论坛)

**Comment by NearlyHeadlessJack** [comment]
还是不行我的action是command “give @p minecraft:torch 1” as op提示I’m sorry but you do not have permission to perform this command发自我的 iPhone在 2023年1月28日，23:23，1217423985 ***@***.***> 写道：﻿我知道问题所在了，没写as op发自我的 iPhone在 2023年1月28日，23:02，1217423985 ***@***.***> 写道：﻿发自我的 iPhone在 2023年1月28日，23:01，1217423985 ***@***.***> 写道：﻿现在又有个这个问题，普通玩家兑换物品（give指令）会这样我用的lp管理权限是哪里的权限节点不合适吗？发自我的 iPhone在 2023年1月28日，10:07，季楠 ***@***.***> 写道：﻿
建议使用物品库类型的插件替代原版指令。
[RPG|管理] NeigeItems —— 万能随机物品库 [1.12.2-1.19.3]
https://www.mcbbs.net/thread-1364195-1-1.html
(出处: Minecraft(我的世界)中文论坛)
